package pascal.orz.cn.example.javaee.apps.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Users entity to verify Jakarta EE 10 migration.
 * Tests Jakarta Bean Validation annotations and custom validators.
 */
@DisplayName("Users Entity Tests")
class UsersTest {

    private Validator validator;

    @BeforeEach
    void setUp() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    @Test
    @DisplayName("Valid user with firstName should pass validation")
    void testValidUserWithFirstName() {
        Users user = new Users();
        user.setFirstName("John");
        user.setAge(30);

        Set<ConstraintViolation<Users>> violations = validator.validate(user);

        assertTrue(violations.isEmpty(), "User with firstName should be valid");
    }

    @Test
    @DisplayName("User with only lastName should fail validation (current validator implementation)")
    void testUserWithOnlyLastName() {
        Users user = new Users();
        user.setLastName("Doe");
        user.setAge(25);

        Set<ConstraintViolation<Users>> violations = validator.validate(user);

        // Note: Current validator implementation only checks firstName, not lastName
        // This test documents the current behavior
        assertFalse(violations.isEmpty(), "User with only lastName fails with current validator");
    }

    @Test
    @DisplayName("Valid user with both firstName and lastName should pass validation")
    void testValidUserWithBothNames() {
        Users user = new Users();
        user.setFirstName("John");
        user.setLastName("Doe");
        user.setAge(30);

        Set<ConstraintViolation<Users>> violations = validator.validate(user);

        assertTrue(violations.isEmpty(), "User with both names should be valid");
    }

    @Test
    @DisplayName("User with empty firstName should fail @Size validation")
    void testUserWithEmptyFirstName() {
        Users user = new Users();
        user.setFirstName("");
        user.setAge(30);

        Set<ConstraintViolation<Users>> violations = validator.validate(user);

        assertFalse(violations.isEmpty(), "User with empty firstName should have violations");
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("firstName")),
                "Violation should be on firstName property");
    }

    @Test
    @DisplayName("User without firstName or lastName should fail @FirstOrLastRequired validation")
    void testUserWithoutNames() {
        Users user = new Users();
        user.setAge(30);

        Set<ConstraintViolation<Users>> violations = validator.validate(user);

        assertFalse(violations.isEmpty(), "User without names should have violations");
    }

    @Test
    @DisplayName("Lombok @Getter and @Setter should work correctly")
    void testLombokAnnotations() {
        Users user = new Users();
        
        // Test setters and getters generated by Lombok
        user.setId(1L);
        user.setFirstName("Jane");
        user.setLastName("Smith");
        user.setAge(28);

        assertEquals(1L, user.getId());
        assertEquals("Jane", user.getFirstName());
        assertEquals("Smith", user.getLastName());
        assertEquals(28, user.getAge());
    }

    @Test
    @DisplayName("Lombok @ToString should work correctly")
    void testLombokToString() {
        Users user = new Users();
        user.setId(1L);
        user.setFirstName("John");
        user.setLastName("Doe");
        user.setAge(30);

        String toString = user.toString();
        
        assertNotNull(toString);
        assertTrue(toString.contains("Users"), "toString should contain class name");
        assertTrue(toString.contains("John"), "toString should contain firstName");
    }

    @Test
    @DisplayName("User entity should be serializable")
    void testSerializable() {
        Users user = new Users();
        
        assertTrue(user instanceof java.io.Serializable, 
                "Users should implement Serializable");
    }

    @Test
    @DisplayName("Multiple validation violations should be detected")
    void testMultipleViolations() {
        Users user = new Users();
        user.setFirstName(""); // Violates @Size(min = 1)
        // No lastName set, violates @FirstOrLastRequired
        user.setAge(30);

        Set<ConstraintViolation<Users>> violations = validator.validate(user);

        assertFalse(violations.isEmpty(), "Should have at least one violation");
    }
}
