services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080" 
      - "4848:4848" 
      - "4900:4900" 
      - "3820:3820" 
      - "3700:3700" 

    command: sleep infinity
